-- MySQL Script generated by MySQL Workbench
-- Fri May 14 21:42:04 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema arforest
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema arforest
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `arforest` DEFAULT CHARACTER SET utf8 ;
USE `arforest` ;

-- -----------------------------------------------------
-- Table `arforest`.`Utilizador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `arforest`.`Utilizador` (
  `idUtilizador` INT NOT NULL AUTO_INCREMENT,
  `nomeUtilizador` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `Senha` VARCHAR(45) NULL,
  PRIMARY KEY (`idUtilizador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `arforest`.`Estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `arforest`.`Estado` (
  `idEstado` INT NOT NULL AUTO_INCREMENT,
  `nomeEstado` VARCHAR(45) NULL,
  PRIMARY KEY (`idEstado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `arforest`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `arforest`.`Categoria` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT,
  `nomeCategoria` VARCHAR(45) NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `arforest`.`Fotografias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `arforest`.`Fotografias` (
  `idFotografias` INT NOT NULL AUTO_INCREMENT,
  `Url` VARCHAR(200) NULL,
  `Classificacao` INT NULL,
  `Latitude` VARCHAR(100) NULL,
  `Longitude` VARCHAR(100) NULL,
  `Data` DATETIME(6) NULL,
  `Fotografias_idEstado` INT NOT NULL,
  `Fotografias_idUtilizador` INT NOT NULL,
  `Fotografias_idCategoria` INT NOT NULL,
  PRIMARY KEY (`idFotografias`, `Fotografias_idEstado`, `Fotografias_idUtilizador`, `Fotografias_idCategoria`),
  INDEX `fk_Fotografias_Estado1_idx` (`Fotografias_idEstado` ASC) VISIBLE,
  INDEX `fk_Fotografias_Utilizador1_idx` (`Fotografias_idUtilizador` ASC) VISIBLE,
  INDEX `fk_Fotografias_Categoria1_idx` (`Fotografias_idCategoria` ASC) VISIBLE,
  CONSTRAINT `fk_Fotografias_Estado1`
    FOREIGN KEY (`Fotografias_idEstado`)
    REFERENCES `arforest`.`Estado` (`idEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fotografias_Utilizador1`
    FOREIGN KEY (`Fotografias_idUtilizador`)
    REFERENCES `arforest`.`Utilizador` (`idUtilizador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fotografias_Categoria1`
    FOREIGN KEY (`Fotografias_idCategoria`)
    REFERENCES `arforest`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `arforest`.`Comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `arforest`.`Comentarios` (
  `idComentarios` INT NOT NULL AUTO_INCREMENT,
  `Titulo` VARCHAR(45) NULL,
  `Texto` VARCHAR(45) NULL,
  `Comentarios_idFotografias` INT NOT NULL,
  `Comentarios_idUtilizador` INT NOT NULL,
  PRIMARY KEY ( `idComentarios`,`Comentarios_idFotografias`, `Comentarios_idUtilizador`),
  INDEX `fk_Comentarios_Utilizador1_idx` (`Comentarios_idUtilizador` ASC) VISIBLE,
  CONSTRAINT `fk_Comentarios_Fotografias1`
    FOREIGN KEY (`Comentarios_idFotografias`)
    REFERENCES `arforest`.`Fotografias` (`idFotografias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comentarios_Utilizador1`
    FOREIGN KEY (`Comentarios_idUtilizador`)
    REFERENCES `arforest`.`Utilizador` (`idUtilizador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
